//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код был создан программным средством.
//
//     Изменения в этом файле могут привести к неправильному поведению и будут утрачены, если
//     код создается повторно.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.view.admin
{


    public partial class rentttt
    {

        /// <summary>
        /// элемент управления form1.
        /// </summary>
        /// <remarks>
        /// Автоматически созданное поле.
        /// Для изменения переместите объявление поля из файла конструктора в файл кода программной части.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// GridViewRents control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView GridViewRents;
    }
}
