//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.view.admin
{

    public partial class slider
    {

        /// <summary>
        /// lblStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblStatus;

        protected global::System.Web.UI.WebControls.Label lblCurrentSlidesHint;

        protected global::System.Web.UI.WebControls.Repeater repCurrentSlides;

        /// <summary>
        /// hfSlideId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField hfSlideId;

        /// <summary>
        /// txtTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtTitle;

        /// <summary>
        /// txtSortOrder control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSortOrder;

        /// <summary>
        /// txtSubtitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSubtitle;

        /// <summary>
        /// fuImage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.FileUpload fuImage;

        /// <summary>
        /// chkActive control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CheckBox chkActive;

        /// <summary>
        /// btnSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSave;

        /// <summary>
        /// btnClear control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClear;

        protected global::System.Web.UI.WebControls.HiddenField hfOrder;

        protected global::System.Web.UI.WebControls.Button btnSaveOrder;

        protected global::System.Web.UI.WebControls.Repeater repOrder;

        /// <summary>
        /// gvSlides control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvSlides;
    }
}
